from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

async def execute_pdf_job(payload: dict) -> str:
    title = payload.get("title", "My Report")
    content = payload.get("content", "Generated by Distributed Job Scheduler")

    output_path = "/app/app/uploads/" + title.replace(" ", "_") + ".pdf"

    print("Generating PDF: " + title)

    c = canvas.Canvas(output_path, pagesize=letter)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(100, 750, title)
    c.setFont("Helvetica", 12)

    y = 700
    for line in content.split("\n"):
        c.drawString(100, y, line)
        y -= 20

    c.save()

    print("PDF generated successfully!")
    return "PDF " + title + " generated successfully!"