from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from app.distributed.circuit_breaker import pdf_breaker

async def execute_pdf_job(payload: dict) -> str:
    title = payload.get("title", "My Report")
    content = payload.get("content", "Generated by Distributed Job Scheduler")

    if not pdf_breaker.can_call():
        raise Exception("PDF service unavailable! Circuit breaker is OPEN!")

    try:
        output_path = "/app/app/uploads/" + title.replace(" ", "_") + ".pdf"

        print("Generating PDF: " + title)

        c = canvas.Canvas(output_path, pagesize=letter)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(100, 750, title)
        c.setFont("Helvetica", 12)

        y = 700
        for line in content.split("\n"):
            c.drawString(100, y, line)
            y -= 20

        c.save()

        pdf_breaker.on_success()
        print("PDF generated successfully!")
        return "PDF " + title + " generated successfully!"

    except Exception as e:
        pdf_breaker.on_failure()
        raise Exception("PDF generation failed: " + str(e))